### ISSUE TITLE
PDF lines are not recognized using the -C option

### ISSUE THREAD

**Issue by adadgio** [Feh/pdfgrep#1]
I've testing the lib on MAC os with the `-C` option and the surrouding lines are recognized okay.

On Debian, with an UTF8 configured server server no lines above and after are shown whatever the value of the `-C` option.

Is there any reason for that ? Here is the PDF.

http://ec.europa.eu/health/documents/community-register/2017/20170803138619/anx_138619_fr.pdf

**Comment by Feh** [comment]
This is a 3-year-old clone of the upstream project, and I’m not a maintainer of that project; can you please report this bug upstream? https://gitlab.com/pdfgrep/pdfgrep/issues
