### ISSUE TITLE
"Building  … is easy. Just use the standard procedure:  ./configure"

### ISSUE THREAD

**Issue by nigelhorne** [Feh/pdfgrep#2]
$ ./configure
-bash: ./configure: No such file or directory
$ ls
AUTHORS		Makefile.am	autogen.sh	exclude.cc	pdfgrep.cc
COPYING		NEWS		completion	exclude.h	www
HACKING		README.asciidoc	configure.ac	output.cc
INSTALL		TODO		doc		output.h

**Comment by Feh** [comment]
This is a 3-year-old clone; can you please report this bug to the original project? Thanks!

**Comment by Feh** [comment]
--> https://gitlab.com/pdfgrep/pdfgrep/issues
